### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/WSManDsc#84]
As per [this statement](https://sfconservancy.org/news/2020/jun/23/gitbranchname/).

**Comment by morrme** [comment]
Do these have to be done by current project maintainers?

**Comment by PlagueHO** [comment]
Hi @morrme - part of the process will most likely have to be done by someone with maintainer privileges to this org. But changes to README.MD and the CI pipeline code will need a PR. I'm going to need to test it out and write it up as an article on dsccommunity.org I think. I've put these issues in as place holders.
